id: A17957F9C
title: f4DA4
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:27:19.805568
  last_modified_at: 2022-05-27 15:27:19.805571
