id: A17957F9C
title: f84EF
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:27:19.821730
  last_modified_at: 2022-05-27 15:27:19.821733
