id: A17957F9C
title: f7AD0
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:27:19.817215
  last_modified_at: 2022-05-27 15:27:19.817218
